#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor

# Defining the text editor to use.
# DMENUEDITOR="st -e vim"
 DMEDITOR="kitty -e nvim"
# DMEDITOR="emacsclient -c -a emacs"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -A options
#options[alacritty]="$HOME/.config/alacritty/alacritty.yml"
options[aliasrc]="$HOME/.config/shell/aliasrc"
options[bashrc]="$HOME/.config/bash/.bashrc"
#options[broot]="$HOME/.config/broot/conf.toml"
options[bspwm]="$HOME/.config/bspwm/bspwmrc"
options[dmenu]="$HOME/.config/dmenu"
options[doom emacs]="$HOME/.doom.d"
options[fehbg]="$HOME/.config/feh/.fehbg"
options[fish]="$HOME/.config/fish/config.fish"
options[kitty]="$HOME/.config/kitty/kitty.conf"
options[nvim]="$HOME/.config/nvim/init.vim"
options[picom]="$HOME/.config/picom/picom.conf"
options[polybar]="$HOME/.config/polybar"
options[scripts]="$HOME/.scripts"
options[spicetify]="$HOME/.config/spicetify/config.ini"
options[sxhkd]="$HOME/.config/sxhkd/sxhkdrc"
options[vimrc]="$HOME/.config/vim/.vimrc"
options[xinitrc_bspwm]="$HOME/.config/xorg/.xinitrc_bspwm"
options[xinitrc_gnome]="$HOME/.config/xorg/.xinitrc_gnome"
options[xresources]="$HOME/.Xresources"
options[zprofile]="$HOME/.config/zsh/.zprofile"
options[zshrc]="$HOME/.config/zsh/.zshrc"

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${!options[@]}" | dmenu -F -h 34 -p 'Edit config:' "$@")


# What to do when/if we choose a file to edit.
if [ "$choice" ]; then
	cfg=$(printf '%s\n' "${options["${choice}"]}")
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 0
fi
